version: '3.8'

services:
  # Backend application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xsha-backend
    ports:
      - "8080:8080"
    environment:
      - XSHA_PORT=8080
      - XSHA_ENVIRONMENT=development
      - XSHA_DATABASE_TYPE=mysql
      - XSHA_MYSQL_DSN=root:password@tcp(mysql:3306)/xsha?charset=utf8mb4&parseTime=True&loc=Local
      - XSHA_ADMIN_USER=admin
      - XSHA_ADMIN_PASS=admin123
      - XSHA_JWT_SECRET=your-jwt-secret-key-change-this-in-production
      - XSHA_WORKSPACE_BASE_DIR=/app/workspaces
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - xsha-network
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: xsha-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=xsha
      - MYSQL_USER=xsha
      - MYSQL_PASSWORD=xshapass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - xsha-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # phpMyAdmin (optional, for database management)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: xsha-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - xsha-network
    restart: unless-stopped
    profiles:
      - tools

# Network configuration
networks:
  xsha-network:
    driver: bridge

# Data volumes
volumes:
  mysql_data:
    driver: local 