version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: sleep0-backend-dev
    ports:
      - "8080:8080"
    environment:
      - SLEEP0_PORT=8080
      - SLEEP0_ENVIRONMENT=development
      - SLEEP0_DATABASE_TYPE=sqlite
      - SLEEP0_SQLITE_PATH=/app/data/app.db
      - SLEEP0_ADMIN_USER=admin
      - SLEEP0_ADMIN_PASS=admin123
      - SLEEP0_JWT_SECRET=dev-jwt-secret
      - SLEEP0_WORKSPACE_BASE_DIR=/app/workspaces
      - SLEEP0_SCHEDULER_INTERVAL=3s
      - SLEEP0_DOCKER_TIMEOUT=30m
      - SLEEP0_GIT_SSL_VERIFY=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app:cached
      - ./runtime/db:/app/data
      - ./runtime/workspaces:/app/workspaces
    restart: unless-stopped
    command: ["air", "-c", ".air.toml"]
