version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: xsha-backend-dev
    ports:
      - "8080:8080"
    environment:
      - XSHA_PORT=8080
      - XSHA_ENVIRONMENT=development
      - XSHA_DATABASE_TYPE=sqlite
      - XSHA_SQLITE_PATH=/app/data/app.db
      - XSHA_ADMIN_USER=admin
      - XSHA_ADMIN_PASS=admin123
      - XSHA_JWT_SECRET=dev-jwt-secret
      - XSHA_WORKSPACE_BASE_DIR=/app/workspaces
      - XSHA_SCHEDULER_INTERVAL=3s
      - XSHA_DOCKER_TIMEOUT=30m
      - XSHA_GIT_SSL_VERIFY=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app:cached
      - ./runtime/db:/app/data
      - ./runtime/workspaces:/app/workspaces
    restart: unless-stopped
    command: ["air", "-c", ".air.toml"]
