services:
  xsha:
    build:
      context: .
      dockerfile: Dockerfile_CN
    container_name: xsha
    ports:
      - "8080:8080"
    environment:
      - XSHA_PORT=8080
      - XSHA_ENVIRONMENT=production
      - XSHA_DATABASE_TYPE=sqlite
      - XSHA_SQLITE_PATH=/app/db/app.db
      - XSHA_JWT_SECRET=your-jwt-secret-key-change-this-in-production
      - XSHA_WORKSPACE_BASE_DIR=/app/xsha-workspaces
      - XSHA_DEV_SESSIONS_DIR=/app/xsha-dev-sessions
      - XSHA_ATTACHMENTS_DIR=/app/xsha-attachments
      - XSHA_MAX_CONCURRENT_TASKS=8
      - XSHA_DOCKER_VOLUME_WORKSPACES=xsha_workspaces
      - XSHA_DOCKER_VOLUME_SESSIONS=xsha_dev_sessions
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - xsha_db:/app/db
      - xsha_workspaces:/app/xsha-workspaces
      - xsha_dev_sessions:/app/xsha-dev-sessions
      - xsha_attachments:/app/xsha-attachments
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  xsha_db:
    name: xsha_db
  xsha_workspaces:
    name: xsha_workspaces
  xsha_dev_sessions:
    name: xsha_dev_sessions
  xsha_attachments:
    name: xsha_attachments