name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
        
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Setup Go cache
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
        
    - name: Build frontend
      run: |
        cd frontend
        pnpm install --frozen-lockfile
        pnpm run build
        
    - name: Build embedded binaries
      run: |
        cd backend
        
        # Create build directory
        mkdir -p build
        
        # Set build variables
        VERSION=${GITHUB_REF_NAME}
        BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        GIT_COMMIT=${GITHUB_SHA::8}
        
        # Build flags with version info
        BUILD_FLAGS="-w -s -X main.Version=${VERSION} -X main.BuildTime=${BUILD_TIME} -X main.GitCommit=${GIT_COMMIT}"
        
        # Build for AMD64
        echo "Building for AMD64..."
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="${BUILD_FLAGS}" -o build/xsha-embedded-linux-amd64 .
        
        # Build for ARM64
        echo "Building for ARM64..."
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="${BUILD_FLAGS}" -o build/xsha-embedded-linux-arm64 .
        
        # Build for Windows AMD64
        echo "Building for Windows AMD64..."
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="${BUILD_FLAGS}" -o build/xsha-embedded-windows-amd64.exe .
        
        # Build for Windows ARM64
        echo "Building for Windows ARM64..."
        CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -ldflags="${BUILD_FLAGS}" -o build/xsha-embedded-windows-arm64.exe .
        
        # Build for macOS AMD64
        echo "Building for macOS AMD64..."
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="${BUILD_FLAGS}" -o build/xsha-embedded-darwin-amd64 .
        
        # Build for macOS ARM64 (Apple Silicon)
        echo "Building for macOS ARM64..."
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="${BUILD_FLAGS}" -o build/xsha-embedded-darwin-arm64 .
        
        # Verify builds
        ls -la build/
        
        # Create checksums
        cd build
        sha256sum xsha-embedded-linux-amd64 > xsha-embedded-linux-amd64.sha256
        sha256sum xsha-embedded-linux-arm64 > xsha-embedded-linux-arm64.sha256
        sha256sum xsha-embedded-windows-amd64.exe > xsha-embedded-windows-amd64.exe.sha256
        sha256sum xsha-embedded-windows-arm64.exe > xsha-embedded-windows-arm64.exe.sha256
        sha256sum xsha-embedded-darwin-amd64 > xsha-embedded-darwin-amd64.sha256
        sha256sum xsha-embedded-darwin-arm64 > xsha-embedded-darwin-arm64.sha256
        
        echo "Build completed successfully!"
        echo "Linux AMD64 size: $(stat -c%s xsha-embedded-linux-amd64 | numfmt --to=iec)"
        echo "Linux ARM64 size: $(stat -c%s xsha-embedded-linux-arm64 | numfmt --to=iec)"
        echo "Windows AMD64 size: $(stat -c%s xsha-embedded-windows-amd64.exe | numfmt --to=iec)"
        echo "Windows ARM64 size: $(stat -c%s xsha-embedded-windows-arm64.exe | numfmt --to=iec)"
        echo "macOS AMD64 size: $(stat -c%s xsha-embedded-darwin-amd64 | numfmt --to=iec)"
        echo "macOS ARM64 size: $(stat -c%s xsha-embedded-darwin-arm64 | numfmt --to=iec)"
        
    - name: Get build info
      id: date
      run: echo "date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
      
    - name: Get Go version
      id: go-version
      run: echo "go-version=$(go version | cut -d' ' -f3)" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## Release ${{ github.ref_name }}
          
          ### Downloads
          - **Linux AMD64**: `xsha-embedded-linux-amd64`
          - **Linux ARM64**: `xsha-embedded-linux-arm64`
          - **Windows AMD64**: `xsha-embedded-windows-amd64.exe`
          - **Windows ARM64**: `xsha-embedded-windows-arm64.exe`
          - **macOS AMD64**: `xsha-embedded-darwin-amd64`
          - **macOS ARM64 (Apple Silicon)**: `xsha-embedded-darwin-arm64`
          
          ### Features
          - Embedded frontend assets (React + TypeScript)
          - Standalone executables (no dependencies required)
          - Cross-platform support (Linux, Windows & macOS, AMD64 & ARM64)
          - Built with Go ${{ steps.go-version.outputs.go-version }}
          
          ### Installation
          #### Linux
          1. Download the appropriate binary for your architecture
          2. Make it executable: `chmod +x xsha-embedded-linux-*`
          3. Run: `./xsha-embedded-linux-*`
          
          #### Windows
          1. Download the appropriate binary for your architecture
          2. Run: `xsha-embedded-windows-*.exe`
          
          #### macOS
          1. Download the appropriate binary for your architecture (Intel: amd64, Apple Silicon: arm64)
          2. Make it executable: `chmod +x xsha-embedded-darwin-*`
          3. Run: `./xsha-embedded-darwin-*`
          
          **Note**: On macOS, you may need to allow the app to run if it's blocked by Gatekeeper:
          - Right-click the binary and select "Open"
          - Or run: `sudo xattr -rd com.apple.quarantine xsha-embedded-darwin-*`
          
          ### Verification
          Verify download integrity using the provided SHA256 checksums:
          
          #### Linux
          ```bash
          # For AMD64
          sha256sum -c xsha-embedded-linux-amd64.sha256
          
          # For ARM64
          sha256sum -c xsha-embedded-linux-arm64.sha256
          ```
          
          #### Windows
          ```powershell
          # For AMD64
          certutil -hashfile xsha-embedded-windows-amd64.exe SHA256
          # Compare with content of xsha-embedded-windows-amd64.exe.sha256
          
          # For ARM64
          certutil -hashfile xsha-embedded-windows-arm64.exe SHA256
          # Compare with content of xsha-embedded-windows-arm64.exe.sha256
          ```
          
          #### macOS
          ```bash
          # For AMD64 (Intel)
          shasum -a 256 -c xsha-embedded-darwin-amd64.sha256
          
          # For ARM64 (Apple Silicon)
          shasum -a 256 -c xsha-embedded-darwin-arm64.sha256
          ```
          
          ### Build Information
          - **Git Commit**: ${{ github.sha }}
          - **Build Date**: ${{ steps.date.outputs.date }}
          - **Go Version**: ${{ steps.go-version.outputs.go-version }}
        files: |
          backend/build/xsha-embedded-linux-amd64
          backend/build/xsha-embedded-linux-amd64.sha256
          backend/build/xsha-embedded-linux-arm64
          backend/build/xsha-embedded-linux-arm64.sha256
          backend/build/xsha-embedded-windows-amd64.exe
          backend/build/xsha-embedded-windows-amd64.exe.sha256
          backend/build/xsha-embedded-windows-arm64.exe
          backend/build/xsha-embedded-windows-arm64.exe.sha256
          backend/build/xsha-embedded-darwin-amd64
          backend/build/xsha-embedded-darwin-amd64.sha256
          backend/build/xsha-embedded-darwin-arm64
          backend/build/xsha-embedded-darwin-arm64.sha256
        draft: false
        prerelease: ${{ contains(github.ref_name, 'rc') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}